### PR TITLE
First stab at 3rdparty requirement setup.

### PR DESCRIPTION
**Pull request by benjyw**
The idea is that `requirements-pants.txt` contains the true direct requirements. That is, only the requirements that are actually directly imported or used by code in this repo. 

Then, `constraints-pants.txt` is a lockfile that pins versions for all those direct requirements, and for their transitive dependencies. Pants is configured to use this lockfile.

The lockfile is generated by a script, `generate_constraints.sh`. It can be tweaked manually if needed, but then the script would need to be more sophisticated - currently it would stomp on any manual tweaks the next time you ran it.

The `requirements-pants.txt`/`constraints-pants.txt` files can replace all the various other requirements files in this repo. When building a deployable artifact (wheel/pex/lambda/etc) Pants will only include the requirements that are actually needed, not the entire constraints file. 

Also in this change:
- A fix to .gitignore to allow BUILD files to be added on case-insensitive filesystems.
- A manual dep on the schema files, as a start towards getting tests to pass. 

With this change, the following example Pants commands work:

`./pants test st2actions/tests/unit/test_action_runner_worker.py` (I did not try other tests).
`./pants lint st2actions/::` (pylint fails but those seem like legit failures).

From my observations, `./pants roots` seem to be set correctly, and `./pants dependencies <file or glob>` seem to be correct.

Notes:

- There may be some direct deps that I missed, in which case they just need to be manually added to `requirements-pants.txt` and the constraints file regenerated.
- I didn't add any version range constraints in `requirements-pants.txt`, but they might be necessary. I don't really know enough about how each one is used.
- The requirements in `contrib/linux` are linux-specific, and only used locally in that directory, so they are not pulled in to the global `requirements-pants.txt`, to avoid complications on non-linux systems.

### CODE REVIEW

**Review by cognifloyd — COMMENTED** [review]
Very cool.

How did you determine which of the dependencies were actually imported / direct dependencies? Grep?

Re: contrib/linux we only support installing on Linux, so that's not an issue.

**Comment by benjyw** [comment]
> How did you determine which of the dependencies were actually imported / direct dependencies? Grep?

It was a bit of a hack: 

I assumed(*) that the existing root-level `requirements.txt` was a superset of the direct dependencies, and created temporary Pants targets out of it using the `python_requirements` macro. Then I ran `./pants dependencies --type=3rdparty ::` to get the union of all actual direct dependencies, as detected by Pants's dependency inference. Then I used those as the basis for `requirements-pants.txt` (and removed the  temporary `python_requirements` macro that was based on the existing `requirements.txt`). 

(*) If my assumption was wrong then there may be some missing deps, but those are easy to add.

**Comment by cognifloyd** [comment]
I merged this, and I'll build a bit more on top of it. If we get to the point of merging it into the main st2, I might have to circle back with you to sign a linux foundation CLA.

**Comment by benjyw** [comment]
Sounds good. Let me know how else we can help.

**Pull request merged**
